### ISSUE TITLE
Nice Vim config layout

### ISSUE THREAD

**Issue by jeaye** [SevereOverfl0w/.files#1]
From https://juxt.pro/blog/posts/vim-1.html I hopped into here and was checking out your Vim configs; they looked so familiar, though, in how they were laid out. Layers, on top of Vim's ftplugin stuff, with specific top-level code to load them. With a closer look, even some code and comments looked identical:

* Yours (Aug 23, 2016): https://github.com/SevereOverfl0w/.files/commit/e5ead5c8c569a8d1fc4f8990bb346e70d134c038#diff-69c3e503fd8548be83f598f8077ac6acR32
* Mine ([Jun 4, 2016](https://github.com/jeaye/vimrc/commit/0030e7ebf7739f8596a9357e497cf8c55d4ebb1e#diff-92573f4f735b4da5d2d72abdc0208b4e)): https://github.com/jeaye/vimrc/blob/master/layer/all-packages.vim#L16

I'm glad the design has been helpful! :smile: It was inspired by a foray into Spacemacs. Please consider attribution, given my copyleft license: https://github.com/jeaye/vimrc/blob/master/LICENSE

**Comment by SevereOverfl0w** [comment]
You're right, I found it in your vimrc at some point and then couldn't re-find where it was originally from.

My vim config has long moved on from layers (although in the past 24 hours I've re-introduced a similar concept based on https://vimways.org/2018/from-vimrc-to-vim/ & some dein features).

If I were still using it, I would add an attribution immediately.
